# Generated by Django 4.1.1 on 2022-11-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_elo_bala_user_elo_rapido'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partidas_jugadas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
